const ROLES = {
  PATIENT: "PATIENT",
  DOCTOR: "DOCTOR",
};

const SLOT_STATUS = {
  AVAILABLE: "AVAILABLE",
  BOOKED: "BOOKED",
};

const APPOINTMENT_STATUS = {
  BOOKED: "BOOKED",
  CANCELLED: "CANCELLED",
};

module.exports = { ROLES, SLOT_STATUS, APPOINTMENT_STATUS };
